#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

DATA=$(cat public/build/environment.json)

if [ "$DATA" != "{\"environment\": \"prod\"}" ]; then
  echo "🚫 You have to compile a production build before pushing to GitHub." && exit 1
else
  echo "✅ Everything is fine, let's push to GitHub."
fi
